--- # MySQL Server single instance installation
- name: Install MySQL Repo
  yum_repository:
    name: mysql-57-yum-entry
    file: mysql-57-yum-entry
    description: "MySQL Community Server 5.7 GA Repo"
    baseurl: "http://repo.mysql.com/yum/mysql-5.7-community/el/{{ ansible_facts['ansible_distribution_major_version'] }}/$basearch/"
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-mysql
    gpgcheck: yes
    enabled: yes
- name: Install MySQL Community Server
  yum:
    name: mysql-community-server
    state: present