--- # Install Filebeat
- name: Install FileBeat
  yum:
    name: filebeat-6.5.4
    state: present
    update_cache: yes
- name: Disable MetricBeat
  service:
    name: filebeat
    enabled: no
    state: stopped