--- # Install Filebeat
- name: Install FileBeat
  yum:
    name: filebeat
    state: latest
    update_cache: yes
- name: Disable MetricBeat
  service:
    name: filebeat
    enabled: no
    state: stopped