- hosts: es-all-nodes
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  roles:
    - es-heartbeat-node
  tasks:
  - name: Install Java OpenJDK 1.8.0
    yum:
      name: java-1.8.0-openjdk
      state: present
  - name: Import Elastic Search GPG-Key
    rpm_key:
      key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      state: present
  - name: Elastic Search Repo file
    template:
      src: beats/templates/es-beats.repo
      dest: /etc/yum.repos.d/es-beats.repo
  - name: Install HeartBeat
    yum:
      name: heartbeat
      state: present
