- hosts: es-kibana-node
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Install Java OpenJDK 1.8.0
    yum:
      name: java-1.8.0-openjdk
      state: present
  - name: Import Elastic Search GPG-Key
    rpm_key:
      key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      state: present
  - name: Kibana Repo file
    template:
      src: kibana/templates/kibana.repo
      dest: /etc/yum.repos.d/kibana.repo
  - name: Install Kibana
    yum:
      name: kibana
      state: present
