--- # Tryout to deploy a Elastic Search Cluster on CentOS 7

- hosts: es-logstash-node
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  roles:
    - logstash
  tasks:
  - name: Install Java OpenJDK 1.8.0
    yum:
      name: java-1.8.0-openjdk
      state: present
  - name: Import Elastic Search GPG-Key
    rpm_key:
      key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      state: present
  - name: Elastic Search Repo file
    template:
      src: base/templates/elasticsearch.repo
      dest: /etc/yum.repos.d/elasticsearch.repo
  - name: Install Elastic Search
    yum:
      name: elasticsearch
      state: present
  - name: Enable Elastic Search Service
    service:
      name: elasticsearch
      enabled: yes
      state: stopped
