---
- name: Import Centos-only tasks (yum)
  import_tasks: redhat.yml
  when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7"

- name: Import RedHat-only tasks (yum)
  import_tasks: redhat.yml
  when: ansible_facts['distribution'] == "Redhat" and ansible_facts['distribution_major_version'] == "7"

- name: Import Debian-only tasks (apt)
  import_tasks: debian.yml
  when: ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] == "9"

- name: Remove previous installations
  package:
    name: percona-xtrabackup
    state: absent

- name: Install Percona Xtrabackup
  package:
    name: percona-xtrabackup-24
    state: latest
