--- # RedHat Installs
# Packages

  - name: Install usual Editors
    yum:
      name: "{{ item }}"
      state: latest
    loop:
      - vim
      - nano

  - name: Get and Extract Micro
    unarchive:
      remote_src: https://github.com/zyedidia/micro/releases/download/v1.4.1/micro-1.4.1-linux64.tar.gz
      creates: /opt/micro/
      dest: /opt/micro/
      extra_opts: ["--strip-components=2"] 

  - name: Create SynLink in /usr/bin
    command: "ln -s /opt/micro/micro /usr/bin/micro"

  - name: Install Micro via snap
    command: snap install micro --classic

  - name: Install clipboard support
    yum:
      name: xclip

  - name: Configure spaces for Vim
    blockinfile:
      create: yes
      backup: yes
      dest: /etc/vimrc
      marker: '" ## {mark} Added by Ansible'
      insertafter: EOF
      content: |
        filetype plugin indent on
        " On pressing tab, insert 2 spaces
        set expandtab
        " show existing tab with 2 spaces width
        set tabstop=2
        set softtabstop=2
        " when indenting with '>', use 2 spaces width
        set shiftwidth=2
