--- # Elasticsearch Repo Registration and base software and requirements
- name: ElasticSearch 6.x Repository Registration for RedHat family OS
  apt_repository:
    name: elasticsearch-6.x
    description: ElasticSearch Repo
    file: elasticsearch
    baseurl: https://artifacts.elastic.co/packages/6.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes
- name: Remove Java any other OpenJDKs
  apt:
    name: java-1.[67].0-openjdk
    state: absent
- name: Install Java OpenJDK 1.8.0
  apt:
    name: java-1.8.0-openjdk
    state: latest
