---
- name: Import Centos-only tasks (yum)
  import_tasks: centos7.yml
  when: (ansible_facts['distribution']|lower == "centos") and 
        (ansible_facts['distribution_major_version' == "7")

- name: Import RedHat-only tasks (yum)
  import_tasks: redhat.yml
  when: (ansible_facts['distribution']|lower == "redhat") and 
        (ansible_facts['distribution_major_version' == "7")

- name: Import Debian-only tasks (apt)
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == "debian"

- name: Install Percona MySQL XDB Cluster Server
  package: 
    name:  Percona-XtraDB-Cluster-full-57
    state: present

- name: Install Percona Xtrabackup
  package:
    name: percona-xtrabackup
    state: present

- name: Enable and start the service
  service:
    name: mysql
    state: started
    enabled: yes