---
- name: Install Percona MySQL Repository
  package:
    name: https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    state: present

- name: Enable the Repository
  command: percona-release setup pxc-57

- name: Refresh YUM Cache
  yum:
    update_cache: yes