--- # Elasticsearch Node playbook. It works for Master/Data Nodes (Configuration required after spin-up)
- hosts: elasticsearch
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  roles:
    - base-tools
    - elasticstack-base
    - elasticsearch-node
    - metricbeat
    - filebeat