--- # Elasticsearch Kibana instance playbook. (Configuration required after spin-up)
- hosts: all
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  roles:
    - base-tools
    - elasticsearch-base
    - kibana
    - metricbeat
    - filebeat