--- # Percona MySQL XDB Cluster playbook
- hosts: all
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  roles:
    - base-tools
    - editors
    - percona-xdb-cluster-57
    - percona-xtrabackup-57