--- # Debian Installs
# Packages
  - name: Install Snap Daemon
    apt:
      name: snapd
      state: latest
  - name: Start Snap Service
    service:
      name: snapd
      enabled: yes
      state: started