--- # RedHat Installs
# Packages
  - name: EPEL Release
    yum:
      name: epel-release
      state: latest
  - name: Snap Daemon
    yum:
      name: snapd
      state: latest
  - name: Create Symbolic link (only for RPM based distros)
    file:
      src: /var/lib/snapd/snap
      dest: /snap
      state: link
  - name: Enable Snap Socket
    command: systemctl enable --now snapd.socket
  - name: Enable and Start Snap Service
    service:
      name: snapd
      enabled: yes
      state: started
