
- name: Create the ansible user
  user:
    name: ansible
    groups: ["users","wheel"]
    createhome: yes
    password: "{{ ansible_passwd }}"
    generate_ssh_key: yes
    ssh_key_file: ansible_rsa
    ssh_key_type: rsa
    update_password: always
    state: present
- name: Enable passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    insertafter: '^root[:space:]ALL'
    line: 'ansible  ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
- name: Copy Authorized SSH Key
  authorized_key:
    key: "{{ ssh_key_file }}"
    user: ansible
    state: present