--- # MySQL Server single instance installation
- name: Install MySQL Repo
  yum_repository:
    name: mysql80-community
    file: mysql80-community
    description: "MySQL 8.0 Community Server"
    baseurl: "http://repo.mysql.com/yum/mysql-8.0-community/el/{{ ansible_distribution_major_version }}/$basearch/"
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-mysql
    gpgcheck: yes
    enabled: yes
- name: Copy MySQL GPG Key
  template:
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-mysql
    src: RPM-GPG-KEY-mysql
    owner: bin
    group: wheel
    mode: 0644
- name: Install MySQL Community Server
  yum:
    name: mysql-community-server
    state: latest
- name: Enable MySQL Service but keep it stopped
  service:
    name: mysqld
    enabled: yes
    state: stopped
