--- # Install Kibana
- name: Install Kibana
  apt:
    name: kibana-6.5.4
    state: present
    update_cache: yes
- name: Disable Kibana for configuration
  service:
    name: kibana
    enabled: no
    state: stopped
