--- # Install Kibana
- name: Install Kibana
  apt:
    name: kibana
    state: latest
    update_cache: yes
- name: Disable Kibana for configuration
  service:
    name: kibana
    enabled: no
    state: stopped
