--- # Suse Installs
- name: Check for DotNet Core Repo
  shell: zypper lr -d | grep microsoft
  register: msrepoexists

- name: Register Microsoft Repo
  zypper_repository:
    auto_import_keys: yes
    overwrite_multiple: yes
    repo: https://packages.microsoft.com/config/opensuse/{{ ansible_distribution_major_version }}/prod.repo
    state: present
  when: msrepoexists.stdout == ""

# Refresh all repos
- zypper_repository:
    repo: '*'
    runrefresh: yes
  
# Packages
- name: Install dotnet core dependencies
  zypper:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - lttng-ust
    - libicu
    - zlib

- name: Install dotnet core
  zypper:
    name: dotnet-sdk-2.2
    state: present