--- # Suse Installs

- name: Register Microsoft Repo
  zypper_repository:
    auto_import_keys: yes
    repo: https://packages.microsoft.com/config/opensuse/{{ ansible_distribution_major_version }}/prod.repo
    state: present

# Refresh all repos
- zypper_repository:
    repo: '*'
    runrefresh: yes
  
# Packages
- name: Install dotnet core dependencies
  zypper:
    name: "{{ item }}"
    state: present
  loop:
    - lttng-ust
    - libcurl
    - openssl-libs
    - krb5-libs
    - libicu
    - zlib

- name: Install powershell core
  zypper:
    name: powershell
    state: present