--- # Suse Installs
- name: Check for DotNet Core Repo
  shell: zypper lr -d | grep microsoft
  register: msrepoexists

- name: Register Microsoft Repo
  zypper_repository:
    auto_import_keys: yes
    overwrite_multiple: yes
    repo: https://packages.microsoft.com/config/opensuse/{{ ansible_distribution_major_version }}/prod.repo
    state: present
  when: msrepoexists.stdout == ""

# Refresh all repos
- name: Refresh Repos
  zypper_repository:
    repo: '*'
    runrefresh: yes
  
# Packages
- name: Install dotnet core dependencies
  zypper:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - lttng-ust
    - libicu
    - libicu-devel
    - libicu-devel-32bit
    - libicu60_2
    - libunwind
    - zlib

- name: Copy missing library
  copy:
    src: libicu52_1.rpm
    dest: /tmp/libicu52_1.rpm

- name: Install missing library
  zypper:
    name: /tmp/libicu52_1.rpm
    state: present

- name: Install dotnet core
  zypper:
    name: dotnet-sdk-2.2
    state: present