--- # Debian-Only tasks
- name: Check/Install Python pre-requisites
  package: 
    name: ["python-dev","libevent-dev"]
    state: present

- name: Upgrade pip
  command: /usr/bin/pip2 install --upgrade pip
  become: yes
  become_method: sudo
