- name: Check/Install Python pre-requisites
  apt: 
    name: ["python","python-pip","gcc","make"]
    state: present
- name: Upgrade pip
  command: /bin/pip2 install --upgrade pip
  become: yes
  become_method: sudo
