- name: Check/Install Python pre-requisites
  yum: 
    name: ["python","python-pip","python-devel","libevent-devel","gcc","make"]
    state: present
- name: Upgrade pip
  command: /bin/pip2 install --upgrade pip
  become: yes
  become_method: sudo
