- name: Check/Install Python pre-requisites
  yum: 
    name: ["python","python-pip","python-devel","libevent-devel","gcc","make"]
    state: present
- name: Upgrade pip
  pip:
    name: python-pip
    state: latest
