--- # Red Hat-only tasks
- name: Check/Install Python pre-requisites
  package: 
    name: ["python-devel","libevent-devel"]
    state: present


- name: Upgrade pip
  command: /bin/pip2 install --upgrade pip
  become: yes
  become_method: sudo
