--- # Base tools for servers and workstations

- name: Include RedHat-only tasks (yum)
  include_tasks: redhat.yml
  when: ansible_facts['distribution']|lower == 'redhat'

- name: Include OpenSUSE-only tasks (yum)
  include_tasks: suse.yml
  when: ansible_facts['distribution']|lower == 'opensuse leap'

- name: Install Midnight Commander
  package:
    name: mc
    state: latest
    update_cache: yes

# - name: Install Progress Bar for piped commands
#   package:
#     name: pv
#     state: latest
#   when: ansible_facts['distribution']|lower != 'amazon'


- name: Install monitoring tools
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - htop
    - iotop

- name: Install monitoring tools
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - atop
    - nload
  when: ansible_facts['distribution']|lower != 'amazon'
  
