--- # Base tools for servers and workstations

- name: Include RedHat-only tasks (yum)
  include_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Install Midnight Commander
  package:
    name: mc
    state: latest

- name: Install Progress Bar for piped commands
  package:
    name: pv
    state: latest

- name: Install monitoring tools
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - htop
    - iotop
    - atop
