--- # RedHat Installs
# Packages
  - name: Install Midnight Commander
    yum:
      name: mc
      state: latest
  - name: Install Progress Bar for piped commands
    yum:
      name: pv
      state: latest
  - name: Install GIT
    yum:
      name: git
      state: latest
  - name: Install Editors
    yum:
      name: 
        - vim
        - nano
      state: latest
  - name: Install monitoring tools
    yum:
      name: 
        - htop
        - iotop
        - atop
        - netstat
      state: latest
