--- # Install Metricbeat
- name: Install MetricBeat
  apt:
    name: metricbeat-6.5.4
    state: present
    update_cache: yes
- name: Disable MetricBeat
  service:
    name: metricbeat
    enabled: no
    state: stopped
