--- # Install and configure MySQL Router

- hosts: ndb-cluster-router
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  roles: 
    - ndb-cluster-router
  tasks:
  - name: Create MySQL Router Config Directory
    file: 
      path: /usr/local/mysql-router
      state: directory
  - name: Install MySQL Router
    yum:
      name: https://dev.mysql.com/get/Downloads/MySQL-Router/mysql-router-8.0.12-1.el7.x86_64.rpm
      state: present
  - name: Deploy config file
    template: 
      src: templates/mysqlrouter.conf
      dest: /usr/local/mysql-rrouter/mysqlrouter.conf
