--- # Elasticsearch Repo Registration and base software and requirements
- name: ElasticSearch 6.x Repository Registration for RedHat family OS
  apt_repository:
    name: elasticsearch-6.x
    description: ElasticSearch Repo
    file: elasticsearch
    baseurl: https://artifacts.elastic.co/packages/6.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes
- name: Install common utility packages and applications
  apt:
    name: ["htop","mc","nano","python-pip","pv","python","vim"]
    state: present
    update_cache: yes
- name: Install Java OpenJDK 1.8.0
  apt:
    name: java-1.8.0-openjdk
    state: present
