--- # Select appropriate playbook according to OS family

- name: Include Linux-only tasks
  include_tasks: linux.yml
  when: ansible_system|lower == 'linux'

- name: Include Windows-only tasks
  include_tasks: windows.yml
  when: ansible_os_family|lower == 'windows'