- name: Set SELinux to permissive mode
  command: setenforce 0

- name: Set SELinux to permissive persistently
  command: sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinu

- name: Enable the br_netfilter module for cluster communication - Step 1
  command: modprobe br_netfilter

- name: Enable the br_netfilter module for cluster communication - Step 2
  command: echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables

- name: Disable SWAP
  command: swapoff -a

- name: Add Docker Repo
  yum_repository:
    name: docker-ce.repo
    