- name: Set SELinux Context for Kubernetes
  command: setenforce 0

- name: Enable the br_netfilter module for cluster communication - Step 1
  command: modprobe br_netfilter

- name: Allow Kubernetes to modify ip tables
  command: echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables

- name: Disable SWAP
  command: swapoff -a

