--- # Install Kubernetes on Ubuntu

- name: Disable Swap
  shell: sudo swapoff -a

- name: Let iptables see bridged traffic
  copy:
    src: etc-sysctl.d-k8s.conf
    dest: /etc/sysctl.d/k8s.conf
    owner: root

- name: Switch to legacy iptables if Ubuntu version  > 18.10
  import_tasks: legacy_iptables_ubuntu.yml
  when: ansible_facts['distribution_major_version']|int >= 18

- name: install pre-requisites
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - apt-transport-https
    - curl

- name: Kubernetes Repository Key Registration for Ubuntu
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Kubernetes Repository Registration for Ubuntu
  apt_repository:
    filename: kubernetes
    #repo: deb https://apt.kubernetes.io/ kubernetes-{{ ansible_facts["distribution_release"] }} main
    repo: deb [trusted=yes] https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    update_cache: yes

- name: Install Kuberetes packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    force: yes
  loop:
    - kubelet=1.18.5*
    - kubeadm=1.18.5*
    - kubectl=1.18.5*
  
- name: Hold Kubernetes packages version
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl

- name: Start and Enable Kubelet
  service:
    name: kubelet
    state: restarted
