- name: Check/Install Python pre-requisites
  apt: 
    name: ["python3","python3-pip","gcc","make"]
    state: present
- name: Upgrade pip
  command: /usr/local/bin/pip3 install --upgrade pip
  become: yes
  become_method: sudo
