--- # Installation steps for Debian/Ubuntu

- name: Check/Install Python pre-requisites
  apt: 
    name: ["python3","python3-pip","python3-dev","libevent-dev","gcc","make"]
    state: latest

- name: Upgrade pip
  command: /usr/bin/pip3 install --upgrade pip
  become: yes
  become_method: sudo
