- name: Check/Install Python pre-requisites
  yum: 
    name: ["python36","python36-pip","python36-devel","libevent-devel","gcc","make"]
    state: present
- name: Upgrade pip
  pip:
    name: python3-pip
    state: latest
