- hosts: workstation
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
#  roles:
#    - local
  tasks:
  - name: Install Java OpenJDK 1.8.0
    yum:
      name: java-1.8.0-openjdk
      state: present
  - name: Install Midnight Commander
    yum:
      name: mc
      state: present
