--- # Install Elasticsearch and Discovery-EC2 plugin
- name: Install Elasticsearch
  apt:
    name: elasticsearch
    state: latest
    update_cache: yes
- name: Install Discovery-EC2 Plugin
  command: /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch discovery-ec2
- name: Disable ElasticSearch
  service:
    name: elasticsearch
    enabled: no
    state: stopped