--- # Select appropriate playbook according to OS family
- name: Install Elasticstack Base first
  include_role:
    name: elasticstack-base
- name: Import RedHat-only tasks
  import_tasks: redhat.yml
  when: ansible_os_family|lower == 'redhat'
- name: Import Debian-only tasks
  import_tasks: debian.yml
  when: ansible_os_family|lower == 'debian'
