--- # Install Metricbeat
- name: Install MetricBeat
  yum:
    name: metricbeat
    state: present
    update_cache: yes
- name: Disable MetricBeat
  service:
    name: metricbeat
    enabled: no
    state: stopped