--- # Cassandra Linux installation
- name: Install pre-requisites
  import_role:
    name: java8-openjdk

- name: Import RedHat-only tasks (yum)
  import_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Import Debian-only tasks (apt)
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Install Cassandra
  package:
    name: cassandra
    state: latest

- name: Copy Config File
  template:
    src: cassandra.yaml.j2
    dest: /etc/cassandra/conf/cassandra.yaml
  notify: restart_cassandra

- name: Copy Cluster Config File
  template:
    src: cassandra-rackdc.properties.j2
    dest: /etc/cassandra/conf/cassandra-rackdc.properties
  notify: restart_cassandra

- name: Copy JVM Config File
  template:
    src: jvm.options.j2
    dest: /etc/cassandra/conf/jvm.options
  notify: restart_cassandra

- name: Remove Topology File
  file:
    name: /etc/cassandra/conf/cassandra-topology.properties
    state: absent
  notify: restart_cassandra

- name: Create Cassandra directory
  file:
    path: /var/lib/cassandra
    owner: cassandra
    group: cassandra
    mode: 775
    state: directory

- name: Create RUN directory
  file:
    path: /var/run/cassandra
    owner: cassandra
    group: cassandra
    mode: 0755
    state: directory
  notify: restart_cassandra

- name: Copy Service File
  copy:
    src: cassandra.service
    dest: /etc/systemd/system/cassandra.service

- name: Enable and start Cassandra
  service:
    name: cassandra
    enabled: yes
    state: started