--- # Cassandra Linux installation
- name: Install pre-requisites
  include_role:
    name: java8-openjdk

- name: Import RedHat-only tasks (yum)
  include_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Import Debian-only tasks (apt)
  include_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Install Cassandra
  package:
    name: cassandra
    state: latest

- name: Copy Cassandra Config File
  template:
    src: cassandra.yaml.j2
    dest: "{{ cassandra_conf_path[ansible_facts['os_family']|lower] }}/cassandra.yaml"

- name: Copy Cluster Config File
  template:
    src: cassandra-rackdc.properties.j2
    dest: "{{ cassandra_conf_path[ansible_facts['os_family']|lower] }}/cassandra-rackdc.properties"

- name: Copy JVM Config File
  template:
    src: jvm.options.j2
    dest: "{{ cassandra_conf_path[ansible_facts['os_family']|lower] }}/jvm.options"

- name: Remove Topology File
  file:
    name: "{{ cassandra_conf_path[ansible_facts['os_family']|lower] }}/cassandra-topology.properties"
    state: absent

- name: Create Cassandra directory
  file:
    path: /var/lib/cassandra
    owner: cassandra
    group: cassandra
    mode: 0777
    state: directory

- name: Create RUN directory
  file:
    path: /var/run/cassandra
    owner: cassandra
    group: cassandra
    mode: 0755
    state: directory
  notify: restart_cassandra

- name: Copy Service File
  copy:
    src: cassandra.service
    dest: /etc/systemd/system/cassandra.service

- name: Enable and start Cassandra
  service:
    name: cassandra
    enabled: yes
    state: started