--- # RedHat Tasks for Cassandra
- name: Cassandra Repository Registration for RedHat family OS
  yum_repository:
    name: Cassandra
    description: Apache Cassandra
    file: apache-cassandra
    baseurl: https://www.apache.org/dist/cassandra/redhat/311x/
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://www.apache.org/dist/cassandra/KEYS
    enabled: yes
    state: present
  notify: yum cache update

- name: Install Cassandra
  yum:
    name: cassandra
    state: latest

- name: Copy Config File
  template:
    src: cassandra.yaml.j2
    dest: /etc/cassandra/conf/cassandra.yaml

- name: Copy Cluster Config File
  template:
    src: cassandra-rackdc.properties.j2
    dest: /etc/cassandra/conf/cassandra-rackdc.properties

- name: Remove Topology File
  file:
    name: /etc/cassandra/conf/cassandra-topology.properties
    state: absent

- name: Enable and start Cassandra
  service:
    name: cassandra
    enabled: no
    state: stopped