--- # RedHat Tasks for Cassandra
- name: Cassandra Repository Registration for RedHat family OS
  yum_repository:
    name: Cassandra
    description: Apache Cassandra
    file: apache-cassandra
    baseurl: https://www.apache.org/dist/cassandra/redhat/311x/
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://www.apache.org/dist/cassandra/KEYS
    enabled: yes
    state: present
  notify: yum_cache_update
