- name: Cassandra Repository Registration for RedHat family OS
  yum_repository:
    name: Apache Cassandra
    description: Apache Cassandra
    file: apache-cassandra-repo
    baseurl: https://www.apache.org/dist/cassandra/redhat/311x/
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://www.apache.org/dist/cassandra/KEYS
    enabled: yes
    state: present
- name: Update Yum cache
  yum:
    name: vi
    update_cache: yes
- name: Install Cassandra
  yum:
    name: cassandra
    state: latest
- name: Enable and start Cassandra
  service:
    name: cassandra
    enabled: yes
    state: started