--- # Elasticsearch Node playbook. It works for Master/Data Nodes (Configuration required after spin-up)
- hosts: la-kibana
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  roles:
    - es-base
    - es-kibana-node