--- # Install Docker on Debian
- name: Install requirements
  apt:
    name: "{{ item }}"
    state: latest
    update-cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Docker Repository Key Registration for Ubuntu
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Docker Repository Registration for Ubuntu
  apt_repository:
    filename: docker-ce
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_facts["distribution_release"] }} stable
    state: present
    update_cache: yes

- name: Install Docker Engine
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io

- name: Enable and start Docker
  service:
    name: docker
    state: started
    enabled: yes
