- name: Import RedHat-only tasks (yum)
  import_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'
- name: Import Debian-only tasks (apt)
  import_tasks: debian.yml
  when: ansible_facts['distribution']|lower == 'debian'
- name: Import Ubuntu-only tasks (apt)
  import_tasks: ubuntu.yml
  when: ansible_facts['distribution']|lower == 'ubuntu' 
