--- # Create User, Groups and Register Repo
- name: Ensure the mysql group exists
  group:
    name: mysql
    state: present
- name: Ensure the mysql user exists
  user:
    name: mysql
    state: present
- name: Download MySQL Repository
  get_url:
    url: https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm
    dest: /tmp/mysql80-community-release-el7-1.noarch.rpm
- name: Install MySQL Repo
  yum:
    name: /tmp/mysql80-community-release-el7-1.noarch.rpm
    state: present
- name: Make sure MariaDB Libs are removed
  yum:
    name: mariadb-libs
    state: absent
- name: Ensure Tar is installed
  yum:
    name: tar
    state: present
