--- # Elasticsearch Node playbook. It works for Master/Data Nodes (Configuration required after spin-up)
- hosts: la-es-nodes
  remote_user: cloud_user
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  roles:
    - es-base
    - es-cluster-node