- name: Import RedHat-only tasks (yum)
  include_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Import Debian-only tasks (apt)
  include_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Import Windows-only tasks
  include_tasks: windows.yml
  when: ansible_facts['os_family']|lower == 'windows'