- name: Include Java8 RedHat-only tasks (yum)
  include_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Include Java8 Debian-only tasks (apt)
  include_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Include Java8 Windows-only tasks
  include_tasks: windows.yml
  when: ansible_facts['os_family']|lower == 'windows'