--- # Elasticsearch Kibana instance playbook. (Configuration required after spin-up)
- hosts: all
  vars_prompt:
<<<<<<< HEAD
  - name: "prompt_for_user"
    prompt: "Do you want to provide remote user info [Y/n]?"
    private: no
  - name: "username"
    prompt: "Enter remote user"
    private: no
    when: prompt_for_user == "Y" or prompt_for_user == "y"
  - name: "password"
    prompt: "Enter password"
    when: prompt_for_user == "Y" or prompt_for_user == "y"
=======
  - name: "username"
    prompt: "Enter remote user"
    private: no
  - name: "password"
    prompt: "Enter password"
>>>>>>> 4eda42804c4e6dd8ba40c6f0364d2288e7d582d8
  vars:
    - ansible_ssh_pass: "{{ password }}"
    - ansible_sudo_pass: "{{ password }}"
  remote_user: "{{ username }}"
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  roles:
    - base-tools
    - elasticsearch-base
    - elasticsearch-kibana
    - elasticsearch-metricbeat
    - elasticsearch-filebeat