--- # Install user and common tools required for development and support.
- hosts: workstation
  vars_prompt:
  - name: "username"
    prompt: "Enter username"
  - name: "password"
    prompt: "Enter password"
    private: yes
    encrypt: "sha512_crypt"
    confirm: yes
    salt_size: 7
  remote_user: "{{ ssh_user }}"
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  roles:
    - linux-base
    - linux-workstation
