- hosts: ndb-cluster-sql
  vars_prompt:
  - name: "username"
    prompt: "Enter remote user"
    private: no
  - name: "password"
    prompt: "Enter password"
  vars:
    - ansible_ssh_pass: "{{ password }}"
    - ansible_sudo_pass: "{{ password }}"
  remote_user: "{{ username }}"
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  roles: 
    - linux-mysql-base
    - linux-mysql-cluster-75
    - linux-mysql-cluster-sql