- hosts: all
  vars_prompt:
  - name: "username"
    prompt: "Enter remote user"
    private: no
  - name: "password"
    prompt: "Enter password"
  - name: mysqlrootpass
    prompt: "MySQL ROOT password"
    private: yes
    confirm: yes
    salt_size: 7
  vars:
    - ansible_ssh_pass: "{{ password }}"
    - ansible_sudo_pass: "{{ password }}"
  remote_user: "{{ username }}"
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  roles:
    - mysql-passwd-reset