--- # Install and configure MySQL Router
- hosts: all
  vars_prompt:
  - name: "prompt_for_user"
    prompt: "Do you want to provide remote user info [Y/n]?"
    private: no
  - name: "username"
    prompt: "Enter remote user"
    private: no
    when: prompt_for_user == "Y" or prompt_for_user == "y"
  - name: "password"
    prompt: "Enter password"
    when: prompt_for_user == "Y" or prompt_for_user == "y"
  vars:
    - ansible_ssh_pass: "{{ password }}"
    - ansible_sudo_pass: "{{ password }}"
  remote_user: "{{ username }}"
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  roles: 
  - linux-mysql-base
  - linux-mysql-cluster-75
  - linux-ndb-router
