- hosts: linuxacademy
  remote_user: cloud_user
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Create the ansible user
    user:
      name: ansible
      groups: ["users","wheel"]
      createhome: yes
      password: "$6$tK.JnuuVmCTYKVSX$6OFFfdfmuvzsfD/cY9EhrdP5qyDcAYQA.WmLcaw8GcJyJ1ydsIDuevxYXkvjfq4cuBLFOFbhn9sdMS4VD37fV/"
      generate_ssh_key: yes
      ssh_key_file: ansible_rsa
      ssh_key_type: rsa
      state: present
  - name: Enable passwordless sudo
    lineinfile:
      path: /etc/sudoers
      state: present
      insertafter: '^root[:space:]ALL'
      line: 'ansible  ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'