- hosts: linuxacademy
  remote_user: cloud_user
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Create the ansible user
    user:
      name: ansible
      groups: ["user","wheel"]
      create_home: yes
      password: "$6$mysecretsalt$VrpJi.TnKITRI6ccD6ryD49I8vr4Iy2sWRNgzxkogL1DZoX2C.gWDHSb3y7GWGW3XNPZ.Df3YuOM7dg0c41uO."
      state: present
  - name: Enable passwordless sudo
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^root[:space:]ALL'
      insertafter: 'ansible  ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'