- hosts: linuxacademy
  remote_user: cloud_user
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Create the ansible user
    user:
      name: ansible
      groups: ["user","wheel"]
      createhome: yes
      password: "$6$mysecretsalt$VrpJi.TnKITRI6ccD6ryD49I8vr4Iy2sWRNgzxkogL1DZoX2C.gWDHSb3y7GWGW3XNPZ.Df3YuOM7dg0c41uO."
      generate_ssh_key: yes
      ssh_key_file: ansible_rsa
      ssh_key_passphrase: "$6$4rc4ng3llt$6hwsUSU1/j2iF/dinV0/99PPtOK5mr0td4DjrXIqPYG6Ssvl8yO0cW8Kbrv/ZmoGWEYf0IRwmbkTH3UfRi7TO."
      ssh_key_type: rsa
      state: present
  - name: Enable passwordless sudo
    lineinfile:
      path: /etc/sudoers
      state: present
      insertafter: '^root[:space:]ALL'
      line: 'ansible  ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'