--- # Handlers
- name: yum-makecache
  command: yum makecache -y
  args:
    warn: no
  listen: yum_cahe_update
  
- name: apt-update
  command: apt update -y
  args:
    warn: no
  listen: apt_update
