--- # Handlers
- name: Update YUM Cache
  command: yum makecache -y
  args:
    warn: no
  listen: yum_cache_update
  
- name: Update APT Cache
  command: apt update -y
  args:
    warn: no
  listen: apt_update

- name: Restart Cassandra
  service:
    name: cassandra
    state: restarted
  listen: restart_cassandra